spring:
  datasource:
    url: jdbc:mysql://34.64.80.52/guestbook
    username: guest
    password: guest1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 34.64.63.209
      port: 6379

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info  # 필요 시 * 로 모든 endpoint 노출
  endpoint:
    health:
      show-details: always    # 헬스 체크 시 상세 정보 포함
