name: CD - Backend Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend to Server

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create private key file
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload deploy scripts to VM
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem ./deploy/*.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deploy/

      - name: Run stop → start → validate
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            bash ~/deploy/stop.sh &&
            bash ~/deploy/start.sh &&
            bash ~/deploy/validate.sh
          '
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
