name: 🚀 CD - Backend Deploy to Server

on:
  workflow_run:
    workflows: ["🧪 CI - Backend Build & Upload JAR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    name: Deploy to VM

    environment:
      name: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'staging' }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar

      - name: Create SSH private key file
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload JAR and deploy scripts to VM
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem ./deploy/*.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deploy/
          scp -o StrictHostKeyChecking=no -i private_key.pem ./*.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deploy/
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Run stop → start → validate
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            bash ~/deploy/stop.sh &&
            bash ~/deploy/start.sh &&
            bash ~/deploy/validate.sh
          '
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
