name: CD - Backend Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend to Server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy by Branch Type
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash ~/deploy/start-main.sh'
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash ~/deploy/start-dev.sh'
          else
            echo "❌ 이 브랜치는 배포 대상이 아닙니다."
            exit 1
          fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          
