name: CI - Backend CI

on:
  push:
    branches: [develop]

jobs:
  build-and-prepare:
    runs-on: ubuntu-22.04

    steps:
      - name: Remove existing backend-service dir
        run: |
          if [ -d "backend-service" ]; then
            echo "🧹 기존 backend-service 삭제 중..."
            rm -rf backend-service
          fi

      - name: Clone backend-service repo
        run: |
          git clone -b develop https://github.com/git-branch-practice/backend-service.git

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Grant Gradle permission
        run: chmod +x backend-service/gradlew

      - name: Build jar
        run: |
          cd backend-service
          ./gradlew bootJar
